# Generated by Django 3.2.7 on 2021-09-25 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bild', models.ImageField(blank=True, null=True, upload_to='artikel_bilder')),
                ('preis', models.DecimalField(decimal_places=2, max_digits=7)),
                ('auf_karte', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bild', models.ImageField(blank=True, null=True, upload_to='kat_bilder')),
            ],
        ),
        migrations.CreateModel(
            name='KioskSeite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', models.ImageField(upload_to='kiosk')),
                ('aktiv', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('bestellt_per', models.CharField(choices=[('TEL', 'Telefonisch'), ('ONLINE', 'Online'), ('DIREKT', 'Direkt')], default='TEL', max_length=15)),
                ('kunden_name', models.CharField(blank=True, max_length=30, null=True)),
                ('kunden_tel', models.CharField(blank=True, max_length=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7)),
                ('ausgedruckt', models.BooleanField(blank=True, default=False)),
                ('benutzer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Einheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mange', models.IntegerField()),
                ('artikel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.artikel')),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.rechnung')),
            ],
        ),
        migrations.AddField(
            model_name='artikel',
            name='kategorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.kategorie'),
        ),
    ]
