# Generated by Django 3.2.7 on 2021-10-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnung',
            name='notiz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
