# Generated by Django 3.2.7 on 2021-10-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_nachricht'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnung',
            name='rechnung_num',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
