# Generated by Django 3.2.7 on 2021-10-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_rechnung_rechnung_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='zutaten',
            field=models.TextField(blank=True, null=True),
        ),
    ]
