# Generated by Django 3.2.7 on 2021-11-02 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_artikel_zutaten'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeistGekaufte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikel_1', to='pos.artikel')),
                ('artikel_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikel_2', to='pos.artikel')),
                ('artikel_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikel_3', to='pos.artikel')),
                ('artikel_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikel_4', to='pos.artikel')),
            ],
        ),
    ]
